# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=100)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationQueue',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=10000)),
                ('doc_id', models.CharField(max_length=1000)),
                ('preprocessed', models.CharField(max_length=10000)),
                ('trainInstance', models.BooleanField()),
                ('margin', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('option', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='NBC_class_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('total_word_count', models.IntegerField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Label')),
            ],
        ),
        migrations.CreateModel(
            name='NBC_vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NBC_word_count_given_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Label')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.NBC_vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='QueueElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposalFlag', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Document')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.AnnotationQueue')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbc_normalized', models.FloatField(default=0.0)),
                ('nbc_prior', models.FloatField(default=0.0)),
                ('nbc_term_given_label', models.FloatField(default=0.0)),
                ('nbc_total', models.FloatField(default=0.0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Document')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Label')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='active_prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation.Label'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Document'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='labels',
            field=models.ManyToManyField(to='annotation.Label'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='proposals',
            field=models.ManyToManyField(related_name='proposals', to='annotation.Label'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
