# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_label_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='preprocessed',
            field=models.CharField(default='toll', max_length=10000),
            preserve_default=False,
        ),
    ]
