# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_annotationqueue_maxannonum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotationqueue',
            old_name='maxAnnoNum',
            new_name='max_anno_num',
        ),
    ]
