# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_auto_20161011_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationqueue',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
