# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0005_annotationqueue_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationqueue',
            name='rank',
        ),
        migrations.AddField(
            model_name='queueelement',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
